# Generated by Django 3.0.2 on 2021-03-16 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 16, 15, 50, 30, 709836, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
