# Generated by Django 3.0.2 on 2021-03-16 16:07

from django.db import migrations, models
import django.db.models.deletion
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_post_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='myapi.Post', validators=[myapi.models.Comment.validate_status]),
        ),
    ]
